delete from games_genres
where Genre = 'Utilities'
    or Genre = 'Animation & Modeling'
    or Genre = 'Video Production' 
    or Genre = 'Photo Editing'
    or Genre = 'Design & Illustration'
    or Genre = 'Education'
    or Genre = 'Software Training'
    or Genre = 'Web Publishing'
    or Genre = 'Audio Production'
    or Genre = 'Accounting'